import * as React from '@lynx-js/react';
import { type ViewProps } from '@lynx-js/types';
declare function Card({ className, ...props }: ViewProps): React.JSX.Element;
declare function CardHeader({ className, ...props }: React.ComponentProps<'view'>): React.JSX.Element;
declare function CardTitle({ className, ...props }: React.ComponentProps<'view'>): React.JSX.Element;
declare function CardDescription({ className, ...props }: React.ComponentProps<'view'>): React.JSX.Element;
declare function CardAction({ className, ...props }: React.ComponentProps<'view'>): React.JSX.Element;
declare function CardContent({ className, ...props }: React.ComponentProps<'view'>): React.JSX.Element;
declare function CardFooter({ className, ...props }: React.ComponentProps<'view'>): React.JSX.Element;
export { Card, CardHeader, CardFooter, CardTitle, CardAction, CardDescription, CardContent, };
