import { StyleSheet } from 'react-native-unistyles';

export const profileStyles = StyleSheet.create((theme) => ({
  container: {
    borderRadius: theme.radii.lg,
    overflow: 'hidden',
    backgroundColor: theme.colors.surfaceElevated,
    borderWidth: 1,
    borderColor: theme.colors.borderSubtle,
  },
  bg: {
    height: 60,
    backgroundColor: theme.colors.accentSoft,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
  },
  content: {
    padding: theme.spacing.lg,
    alignItems: 'center',
    gap: theme.spacing.sm,
  },
  avatarLarge: {
    width: 72,
    height: 72,
    borderRadius: theme.radii.lg,
    backgroundColor: theme.colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  avatarCreate: {
    backgroundColor: 'transparent',
    borderStyle: 'dashed',
  },
  createTitle: {
    color: theme.colors.textPrimary,
    fontWeight: '700',
    fontSize: theme.typography.heading.fontSize,
  },
  createSubtitle: {
    color: theme.colors.textSecondary,
    fontSize: theme.typography.caption.fontSize,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceMuted,
    borderRadius: theme.radii.pill,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: theme.colors.border,
    width: '100%',
    gap: theme.spacing.xs,
    marginTop: theme.spacing.md,
  },
  atSymbol: {
    color: theme.colors.textMuted,
    fontSize: 14,
  },
  input: {
    flex: 1,
    color: theme.colors.textPrimary,
    fontSize: 14,
    fontWeight: '600',
    paddingVertical: 8,
  },
  anchorButton: {
    backgroundColor: theme.colors.textPrimary,
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  anchorButtonDisabled: {
    backgroundColor: theme.colors.border,
  },
  avatarText: {
    fontSize: 28,
    color: theme.colors.indicator.profile,
    fontWeight: '700',
  },
  name: {
    color: theme.colors.textPrimary,
    fontWeight: '700',
    fontSize: theme.typography.heading.fontSize,
  },
  handle: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption.fontSize,
    fontFamily: 'monospace',
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.xs,
    backgroundColor: theme.colors.accentSoft,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: 4,
    borderRadius: theme.radii.md,
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginTop: theme.spacing.xs,
  },
  badgeIcon: {
    color: theme.colors.accent,
  },
  badgeText: {
    color: theme.colors.accent,
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  bio: {
    width: '100%',
    color: theme.colors.textSecondary,
    fontSize: theme.typography.body.fontSize,
    lineHeight: 20,
    textAlign: 'center',
    marginTop: theme.spacing.xs,
  },
  statsRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: theme.colors.surfaceMuted,
    borderRadius: theme.radii.md,
    borderWidth: 1,
    borderColor: theme.colors.borderSubtle,
    paddingVertical: theme.spacing.sm,
    paddingHorizontal: theme.spacing.md,
    marginTop: theme.spacing.sm,
  },
  stat: {
    alignItems: 'center',
    flex: 1,
  },
  statValue: {
    color: theme.colors.textPrimary,
    fontWeight: '700',
    fontSize: 14,
  },
  statLabel: {
    color: theme.colors.textMuted,
    fontSize: 11,
    marginTop: 2,
    textTransform: 'uppercase',
  },
  keyContainer: {
    width: '100%',
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderSubtle,
    borderRadius: theme.radii.md,
    padding: theme.spacing.md,
    marginTop: theme.spacing.sm,
    gap: theme.spacing.xs,
  },
  keyLabel: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption.fontSize,
    textTransform: 'uppercase',
  },
  keyValue: {
    color: theme.colors.textSecondary,
    fontFamily: 'monospace',
    fontSize: 12,
  },
}));
